/**
 * Chứa các tên action để dispatch cho reducer hoặc Saga
 */

/**
 ****** APP ACTIONS ******
 **/
export const APP = {
  GET_MODELS_ASYNC: 'GET_MODELS_ASYNC',
  GET_MODELS_END: 'GET_MODELS_END',
  GET_SCHEDULE_TODAY_ASYNC: 'GET_SCHEDULE_TODAY_ASYNC',
  GET_SCHEDULE_TODAY_END: 'GET_SCHEDULE_TODAY_END',
  GET_SERVICE_ASYNC: 'GET_SERVICE_ASYNC',
  GET_SERVICE_END: 'GET_SERVICE_END',
  BOOKING_ASYNC: 'BOOKING_ASYNC',
  BOOKING_START: 'BOOKING_START',
  BOOKING_END: 'BOOKING_END',
  GET_HOME_SERVICE_ASYNC: 'GET_HOME_SERVICE_ASYNC',
  GET_HOME_SERVICE_END: 'GET_HOME_SERVICE_END',
  PUT_INFO_BOOKING: 'PUT_INFO_BOOKING',
  GET_ACCESSORIES_ASYNC: 'GET_ACCESSORIES_ASYNC',
  GET_ACCESSORIES_END: 'GET_ACCESSORIES_END',
  GET_SLICE_ACCESSORIES_ASYNC: 'GET_SLICE_ACCESSORIES_ASYNC',
  GET_SLICE_ACCESSORIES_END: 'GET_SLICE_ACCESSORIES_END',
  GET_BRAND_ASYNC : 'GET_BRAND_ASYNC',
  GET_BRAND_END : 'GET_BRAND_END',
  GET_ACTIVITY_TOP_ASYNC: 'GET_ACTIVITY_TOP_ASYNC',
  GET_ACTIVITY_TOP_END : 'GET_ACTIVITY_TOP_END',
  GET_OIL_ASYNC : 'GET_OIL_ASYNC',
  GET_OIL_END: 'GET_OIL_END',

  GET_HOME_INFO_ASYNC: 'GET_HOME_INFO_ASYNC',
  GET_HOME_INFO_END: 'GET_HOME_INFO_END',

  GET_ORDER_BY_PHONE_ASYNC: 'GET_ORDER_BY_PHONE_ASYNC',
  GET_ORDER_BY_PHONE_END: 'GET_ORDER_BY_PHONE_END',

  CHANGE_STATUS_SEARCH_PHONE_MODAL : 'CHANGE_STATUS_SEARCH_PHONE_MODAL',
  CHANGE_MODE_BOOKING_MODAL: 'CHANGE_MODE_BOOKING_MODAL',

  CANCEL_BOOKING_ASYNC : 'CANCEL_BOOKING_ASYNC',
  CANCEL_BOOKING_END : 'CANCEL_BOOKING_END',

  UPDATE_ORDER_ASYNC: 'UPDATE_ORDER_ASYNC',
  UPDATE_ORDER_END: 'UPDATE_ORDER_END'
}
