/**
 * Chứa các tên action để dispatch cho reducer hoặc Saga
 */

/**
 ****** APP ACTIONS ******
 **/
export const APP = {
  GET_MODELS_ASYNC: 'GET_MODELS_ASYNC',
  GET_MODELS_END: 'GET_MODELS_END',
  GET_SCHEDULE_TODAY_ASYNC: 'GET_SCHEDULE_TODAY_ASYNC',
  GET_SCHEDULE_TODAY_END: 'GET_SCHEDULE_TODAY_END',
  GET_SERVICE_ASYNC: 'GET_SERVICE_ASYNC',
  GET_SERVICE_END: 'GET_SERVICE_END',
  BOOKING_ASYNC: 'BOOKING_ASYNC',
  BOOKING_START: 'BOOKING_START',
  BOOKING_END: 'BOOKING_END',
  GET_HOME_SERVICE_ASYNC: 'GET_HOME_SERVICE_ASYNC',
  PUT_INFO_BOOKING: 'PUT_INFO_BOOKING',
  GET_ACCESSORIES_ASYNC: 'GET_ACCESSORIES_ASYNC',
  GET_ACCESSORIES_END: 'GET_ACCESSORIES_END'
}
