/**
 * Chứa các tên action để dispatch cho reducer hoặc Saga
 */

/**
 ****** APP ACTIONS ******
 **/
export const APP = {
  GET_LIST_BOOKING_ASYNC : 'GET_LIST_BOOKING_ASYNC',
  GET_LIST_BOOKING_END: 'GET_LIST_BOOKING_END',

  GET_BOOKING_DETAIL_ASYNC: 'GET_BOOKING_DETAIL_ASYNC',
  GET_BOOKING_DETAIL_END : 'GET_BOOKING_DETAIL_END',

  GET_ORDERS_BY_STATUS_ASYNC: 'GET_ORDERS_BY_STATUS_ASYNC',
  GET_ORDERS_BY_STATUS_END : 'GET_ORDERS_BY_STATUS_END',

  UPDATE_STATUS_ASYNC: 'UPDATE_STATUS_ASYNC',
  UPDATE_STATUS_END: 'UPDATE_STATUS_END'
}
