/**
 * Chứa các tên action để dispatch cho reducer hoặc Saga
 */

/**
 ****** APP ACTIONS ******
 **/
export const APP = {
  GET_LIST_BOOKING_ASYNC : 'GET_LIST_BOOKING_ASYNC',
  GET_LIST_BOOKING_END: 'GET_LIST_BOOKING_END',

  GET_BOOKING_DETAIL_ASYNC: 'GET_BOOKING_DETAIL_ASYNC',
  GET_BOOKING_DETAIL_END : 'GET_BOOKING_DETAIL_END',

  GET_ORDERS_BY_STATUS_ASYNC: 'GET_ORDERS_BY_STATUS_ASYNC',
  GET_ORDERS_BY_STATUS_END : 'GET_ORDERS_BY_STATUS_END',

  UPDATE_STATUS_ASYNC: 'UPDATE_STATUS_ASYNC',
  UPDATE_STATUS_END: 'UPDATE_STATUS_END',

  GET_EMPLOYES_ASYNC: 'GET_EMPLOYES_ASYNC',
  GET_EMPLOYES_END: 'GET_EMPLOYES_END',

  ASSIGN_EMPLOYEE_ASYNC : 'ASSIGN_EMPLOYEE_ASYNC',
  ASSIGN_EMPLOYEE_END : 'ASSIGN_EMPLOYEE_END',

  GET_SERVICE_ASYNC: 'GET_SERVICE_ASYNC',
  GET_SERVICE_END: 'GET_SERVICE_END',

  GET_SCHEDULE_ASYNC: 'GET_SCHEDULE_ASYNC',
  GET_SCHEDULE_END: 'GET_SCHEDULE_END',

  UPDATE_ORDER_ASYNC: 'UPDATE_ORDER_ASYNC',
  UPDATE_ORDER_END : 'UPDATE_ORDER_END',

  GET_ORDER_BY_USER_ASSIGNED_ASYNC : 'GET_ORDER_BY_USER_ASSIGNED_ASYNC',
  GET_ORDER_BY_USER_ASSIGNED_END : 'GET_ORDER_BY_USER_ASSIGNED_END',

  GET_ORDER_BY_STATUS_DATE_ASYNC: 'GET_ORDER_BY_STATUS_DATE_ASYNC',
  GET_ORDER_BY_STATUS_DATE_END: 'GET_ORDER_BY_STATUS_DATE_END'

}
